# Site settings
title: angular-packery
description: An AngularJS module for the Packery bin-packing library
maintainer: SunGard-Labs
repo: https://github.com/sungard-labs
google-analytics: "UA-16186421-5"
keywords: [
  'packery',
  'angular',
  'layout',
  'bin',
  'binpacking',
  'packing',
  'outlayer',
  'sungard',
  'sungard-labs',
  'demo',
  'demos'
]

# Build settings
markdown: kramdown
exclude: [
  'bower.json',
  'resources/lib/angular-packery/src',
  'resources/lib/angular-packery/bower.json',
  'resources/lib/angular-packery/Gruntfile.js',
  'resources/lib/angular-packery/LICENSE',
  'resources/lib/angular-packery/package.json',
  'resources/lib/angular-packery/README.MD'
]
